inherit_from:
  - https://raw.githubusercontent.com/cookpad/guides/master/.rubocop.yml

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  Exclude:
    - vendor/**/*
    - vendor/**/.*

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Rails/RakeEnvironment:
  Enabled: false
