inherit_from:
  - https://raw.githubusercontent.com/cookpad/guides/master/.rubocop.yml

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - vendor/**/*
    - vendor/**/.*

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

